version: '3'
services:

  eureka:
    image: gatewayservice-arisanonline
    container_name: gatewayservice-arisanonline
    build:
      context: ./gatewayservice-arisanonline
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - dbmysql
  
  document:
    image: documentationservice-arisanonline 
    container_name: documentationservice-arisanonline
    build:
      context: ./documentationservice-arisanonline
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      - dbmysql
      - eureka
    links: 
      - dbmysql
      - eureka

  account:
    image: registerservice-arisanonline
    container_name: registerservice-arisanonline
    build:
      context: ./registerservice-arisanonline
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - dbmysql
      - eureka
    links: 
      - dbmysql
      - eureka
 
  grupservice:
    image: groupsservice
    container_name: groupsservice
    build:
      context: ./groupsservice
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - dbmysql
      - eureka
    links:
      - dbmysql
      - eureka

  dbmysql:
    container_name: docker-local-mysql
    image: mysql:5.7.18
    volumes:
      - "./data:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: --default-authentication-plugin=mysql_native_password

      
      
